name: Go package

on: [push]

jobs:
  list-manifests:
    runs-on: ubuntu-latest
    outputs:
      locs: ${{ steps.get-go-folders.outputs.locs }}
    steps:
      - uses: actions/checkout@v2
      - id: get-go-folders
        run: echo "::set-output name=locs::$(go list -m | sed "s/github.com\/teraptra\/base//" | awk 'NF{print $$0 "/..."}')"
  golangci:
    needs: list-manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.53
          args: --config ./.github/golangci.yml ${{needs.list-manifests.outputs.locs}}
  go-build:
    needs: list-manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: go build -o bin/ -v ${{needs.list-manifests.outputs.locs}}

      - name: Test
        run: go test -v -race ${{needs.list-manifests.outputs.locs}}